### ISSUE TITLE
The best AC86U solution! And one more question.

### ISSUE THREAD

**Issue by leonlianght** [Acris/shadowsocks-asuswrt-merlin#5]
This is the best solution for AC86U, thank you Acris!!!

There is an issue during my setup: I have a server that the IP will be changed regularly, and I am using DDNS to bind a domain to this server.
When I tried to config the ss I found that I had to put the domain into `user_domain_name_gfwlist.txt` to force it passing through proxy, otherwise the proxy won't work, however I can dig the domain with correct IP without proxy. Not sure if it is an issue.

**Comment by Acris** [comment]
Can you run `ss-merlin upgrade` and test whether the issue still exists, remember to remove your domain name from `user_domain_name_gfwlist.txt`.
BTW, I do not recommend to use a domain instead of an IP address, because when the IP changed, even if you use the domain name, the new IP will not take effect unless you reboot shadowsocks.

**Comment by leonlianght** [comment]
Thanks for your replay.
I am away from home and will test it next Monday and let you know asap.
If the new IP will not take effect I might write a script to track the IP and reboot it if necessary.

**Comment by leonlianght** [comment]
Sorry my ss server is down and I am waiting for it to reboot... Will test it and let u know when it comes back.

**Comment by Acris** [comment]
Temporarily closed this issue due to no further activity occurs, feel free to re-open it if needed.
